### ISSUE TITLE
Problems with Dialog File

### ISSUE THREAD

**Issue by moritzbe** [biosopher/watson-ipa-web-nodejs#2]
Running the app locally works fine, but pushing it to Bluemix causes an error with the dialog file.

Great App btw. Im very impressed!

**Comment by biosopher** [comment]
What error are you seeing?  I have the file running in Bluemix.

**Comment by moritzbe** [comment]
Hi, If you go to http://ipa-demo-anthony.mybluemix.net/, it cannot load the dialog. I couldn´t locate the error.

**Comment by biosopher** [comment]
Thanks for pointing out that the demo site was down.  This wasn't a coding error, but just my mistake in not updating my demo server properly. 

I just posted a couple updates to the dialog XML though.  Should make the experience more intuitive when testing for the first time.  I recommend downloading those and re-pushing your app to Bluemix.

Also ensure you update the name section of your manifest.yml to point to your own server name.
