### ISSUE TITLE
Does NLC support wild card (*) in the training data ?

### ISSUE THREAD

**Issue by hkomine** [biosopher/watson-ipa-web-nodejs#4]
Sorry that this is a question rather than issue report.
My business partner found your training data sample contains wildcard (*) and asked me if NLC training data support wildcard or regular expression. I believe that NLC does not.
But I would like to confirm your intent why you put wildcard in the training data. I expect that you used "Email *" because you did not want put any specific names/mail-addresses in the training data like "Email Anthony"
Is my expectation correct ?

**Comment by biosopher** [comment]
Hi @hkomine.  NLC does not support wildcards and the asterisks are there simply as a mental placeholder when reviewing the training pairs.  It's also a reminder not to clutter your NLC training set with entities/keywords that can appear in multiple places.

**Comment by hkomine** [comment]
Thanks for your quick response. I understand that. 
Best regards,
